defaults:

  logdir: null
  traindir: null
  evaldir: null
  offline_traindir: ''
  offline_evaldir: ''
  seed: 0
  deterministic_run: False
  steps: 1e6
  parallel: False
  eval_every: 2e5 
  eval_episode_num: 10
  log_every: 1e4
  reset_every: 0
  device: 'cuda:3'
  compile: True
  precision: 32
  debug: False
  video_pred_log: True
  use_pixel_shift: False
  pixel_shift_prob: 0.2
  wandb_exp: "default-exp"
  wandb_proj: "default-proj"

  # Environment
  task: 'dmc_walker_walk'
  size: [64, 64]
  envs: 1
  action_repeat: 2
  time_limit: 1000
  grayscale: False
  prefill: 2500
  reward_EMA: True

  # Model
  dyn_hidden: 512
  dyn_deter: 512
  dyn_stoch: 32
  dyn_discrete: 32
  dyn_rec_depth: 1
  dyn_mean_act: 'none'
  dyn_std_act: 'sigmoid2'
  dyn_min_std: 0.1
  grad_heads: ['decoder', 'reward', 'cont']
  units: 512
  act: 'SiLU'
  norm: True
  encoder:
    {mlp_keys: '$^', cnn_keys: 'image', act: 'SiLU', norm: True, cnn_depth: 32, kernel_size: 4, minres: 4, mlp_layers: 5, mlp_units: 1024, symlog_inputs: True}
  decoder:
    {mlp_keys: '$^', cnn_keys: 'image', act: 'SiLU', norm: True, cnn_depth: 32, kernel_size: 4, minres: 4, mlp_layers: 5, mlp_units: 1024, cnn_sigmoid: False, image_dist: mse, vector_dist: symlog_mse, outscale: 1.0}
  actor:
    {layers: 2, dist: 'normal', entropy: 3e-4, unimix_ratio: 0.01, std: 'learned', min_std: 0.1, max_std: 1.0, temp: 0.1, lr: 3e-5, eps: 1e-5, grad_clip: 100.0, outscale: 1.0}
  critic:
    {layers: 2, dist: 'symlog_disc', slow_target: True, slow_target_update: 1, slow_target_fraction: 0.02, lr: 3e-5, eps: 1e-5, grad_clip: 100.0, outscale: 0.0}
  reward_head:
    {layers: 2, dist: 'symlog_disc', loss_scale: 1.0, outscale: 0.0}
  cont_head:
    {layers: 2, loss_scale: 1.0, outscale: 1.0}
  dyn_scale: 0.5
  rep_scale: 0.1
  kl_free: 1.0
  weight_decay: 0.0
  unimix_ratio: 0.01
  initial: 'learned'

  # Training
  batch_size: 16
  batch_length: 64
  train_ratio: 512
  pretrain: 100
  model_lr: 1e-4
  opt_eps: 1e-8
  grad_clip: 1000
  dataset_size: 1000000
  opt: 'adam'

  # Behavior.
  discount: 0.997
  discount_lambda: 0.95
  imag_horizon: 15
  imag_gradient: 'dynamics'
  imag_gradient_mix: 0.0
  eval_state_mean: False

  # Exploration
  expl_behavior: 'greedy'
  expl_until: 0
  expl_extr_scale: 0.0
  expl_intr_scale: 1.0
  disag_target: 'stoch'
  disag_log: True
  disag_models: 10
  disag_offset: 1
  disag_layers: 4
  disag_units: 400
  disag_action_cond: False

dmc_proprio:
  steps: 5e5
  action_repeat: 2
  envs: 4
  train_ratio: 512
  video_pred_log: false
  encoder: {mlp_keys: '.*', cnn_keys: '$^'}
  decoder: {mlp_keys: '.*', cnn_keys: '$^'}

dmc_vision:
  steps: 1e6
  action_repeat: 2
  envs: 4
  train_ratio: 512
  video_pred_log: true
  encoder: {mlp_keys: '$^', cnn_keys: 'image'}
  decoder: {mlp_keys: '$^', cnn_keys: 'image'}

crafter:
  task: crafter_reward
  step: 1e6
  action_repeat: 1
  envs: 1
  train_ratio: 512
  video_pred_log: true
  dyn_hidden: 1024
  dyn_deter: 4096
  units: 1024
  encoder: {mlp_keys: '$^', cnn_keys: 'image', cnn_depth: 96, mlp_layers: 5, mlp_units: 1024}
  decoder: {mlp_keys: '$^', cnn_keys: 'image', cnn_depth: 96, mlp_layers: 5, mlp_units: 1024}
  actor: {layers: 5, dist: 'onehot', std: 'none'}
  value: {layers: 5}
  reward_head: {layers: 5}
  cont_head: {layers: 5}
  imag_gradient: 'reinforce'

atari100k:
  steps: 4e5
  envs: 1
  action_repeat: 4
  train_ratio: 1024
  video_pred_log: true
  eval_episode_num: 30 #100
  actor: {dist: 'onehot', std: 'none'}
  imag_gradient: 'reinforce'
  stickey: False
  lives: unused
  noops: 30
  resize: opencv
  actions: needed
  time_limit: 108000

minecraft:
  task: minecraft_diamond
  step: 1e8
  parallel: True
  envs: 16
  # no eval
  eval_episode_num: 0
  eval_every: 1e4
  action_repeat: 1
  train_ratio: 16
  video_pred_log: true
  dyn_hidden: 1024
  dyn_deter: 4096
  units: 1024
  encoder: {mlp_keys: 'inventory|inventory_max|equipped|health|hunger|breath|obs_reward', cnn_keys: 'image', cnn_depth: 96, mlp_layers: 5, mlp_units: 1024}
  decoder: {mlp_keys: 'inventory|inventory_max|equipped|health|hunger|breath', cnn_keys: 'image', cnn_depth: 96, mlp_layers: 5, mlp_units: 1024}
  actor: {layers: 5, dist: 'onehot', std: 'none'}
  value: {layers: 5}
  reward_head: {layers: 5}
  cont_head: {layers: 5}
  imag_gradient: 'reinforce'
  break_speed: 100.0
  time_limit: 36000

memorymaze:
  steps: 1e8
  action_repeat: 2
  actor: {dist: 'onehot', std: 'none'}
  imag_gradient: 'reinforce'
  task: 'memorymaze_9x9'

debug:
  debug: True
  pretrain: 1
  prefill: 1
  batch_size: 10
  batch_length: 20
  eval_episode_num: 1


updates:
  video_pred_log: True
  actor_layers: 2

# acro
  use_acro_loss: False
  acro_K: 16
  use_bottleneck: False
  use_count_based_exploration: False
  bottleneck_params: {"pred_dim": 128, "proj_dim": 64, "num_protos": 512, "tau": 0.1, "topk": 3, "queue_size": 2048, "encoder_target_tau": 0.05}
  
# ICM
  use_icm_loss: False
  eta: 1.0

# extra loss
  use_extra_loss: True
  

# JEPA
  use_ijepa_loss: False
  ijepa_params: {"proj_dim":4096, "n_patches":64, "embed_dim":64, "enc_heads":8, "enc_depth":4, "decoder_depth":6,"num_target": 4,"layer_dropout": 0.0,"post_emb_norm": False, "target_aspect_ratio": [0.75, 1.5], "target_scale": [0.15, 0.2], "context_aspect_ratio": 1, "context_scale": [0.85, 1.0], "m": 0.996, "m_start_end": [0.996, 1.0], should_patch: True}

  use_tjepa_loss: False
  tjepa_params: {"proj_dim":64, "n_patches":64, "embed_dim":64, "enc_heads":8, "enc_depth":4, "decoder_depth":6,"num_target": 4,"layer_dropout": 0.0,"post_emb_norm": False, "target_aspect_ratio": [0.75, 1.5], "target_scale": [0.15, 0.2], "context_aspect_ratio": 1, "context_scale": [0.85, 1.0], "m": 0.996, "m_start_end": [0.996, 1.0], should_patch: False}

  # device: 'cuda:3'
  # max_hierarchy: 1
  # batch_size: 16

# mlr
  use_mlr_loss: False
  patch_size: 8
  mask_ratio: 0.5

# atp
  use_atp_loss: False

# shift pixel
  use_pixel_shift: False

mlr:
  use_mlr_loss: True
 
acro:
  use_acro_loss: True
  actor_dist: 'onehot'
  action_unimix_ratio: 0.01
  acro_norm: 'LayerNorm'

icm:
  use_icm_loss: True
  actor_dist: 'onehot'
  eta: 1.0

atp:
  use_atp_loss: True
  atp_tau: 0.01

pixel_shift:
  use_pixel_shift: True
  # pixel_shift_prob: 0.2
